name: locallense
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # Localization
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2 # Dependency Injection
  logging: 1.2.0 # Logger
  intl: ^0.19.0 # Localization
  connectivity_plus: ^6.0.3 # Internet connection check
  shared_preferences: 2.2.3 # Local storage
  json_annotation: ^4.9.0 # Annotations for json generator
  flutter_svg: ^2.0.10+1 # Svg to widget
  sentry_flutter: ^8.4.0 # Crash analytics
  retrofit: ^4.1.0 # Network calls
  mobx: ^2.3.3+2 # State manager
  flutter_mobx: ^2.2.1+1 # State manager widgets
  flutter_secure_storage: ^9.2.2 # Local storage for sensitive data
  dio: ^5.5.0+1 # Added to avoid warning
  device_preview: ^1.2.0 # Device Preview
  screwdriver: ^5.4.0
  freezed_annotation:
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.0
  latlong2: ^0.9.1
  image_picker:
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.2 # Network calls gen
  build_runner: ^2.4.11 # Code generator
  json_serializable: ^6.8.0 # Json serialization gen
  mobx_codegen: ^2.6.1 # Mobx state manager gen
  flutter_gen_runner: ^5.6.0 # Asset code gen
  very_good_analysis: ^6.0.0 # Linter
  freezed:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  analyzer:
  meta:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Black.ttf
        - asset: assets/fonts/Jost-Italic.ttf
          style: italic
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Light.ttf
          weight: 200
        - asset: assets/fonts/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 500

flutter_gen:
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: Str

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  ios: false
